objects/Dynamic_UI__c.object
<CustomObject>
    <fields>
        <fullName>Grid_Structure__c</fullName>
        <label>Grid Structure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OneColumnLayout</fullName>
                </value>
                <value>
                    <fullName>TwoColumnLayout</fullName>
                </value>
                <value>
                    <fullName>ThreeColumnLayout</fullName>
                </value>
                <value>
                    <fullName>TwoOneLayout</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dynamic UI</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dynamic UI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dynamic_UI_Elements__c.object
<CustomObject>
    <fields>
        <fullName>Component_Name__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Position__c</fullName>
        <label>Component Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Config_Data__c</fullName>
        <label>Config Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Dynamic_UI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dynamic UI</label>
        <referenceTo>Dynamic_UI__c</referenceTo>
        <relationshipLabel>Dynamic UI Elements</relationshipLabel>
        <relationshipName>Dynamic_UI_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dynamic UI Elements</label>
    <nameField>
        <displayFormat>DUE-{0000}</displayFormat>
        <label>Dynamic UI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dynamic UI Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GetDynamicComponentData.cls
public class GetDynamicComponentData {
    
    @AuraEnabled
    public static Dynamic_UI__c getUiDetails(String uiElementName){
        
        return [select id,Grid_Structure__c,(select id,Component_Name__c,Config_Data__c,Component_Position__c from Dynamic_UI_Elements__r) from Dynamic_UI__c where name=:uiElementName];
    }
    
     @AuraEnabled
    public static Dynamic_UI_Elements__c getSingleUiDetailsforHtml(){
        
        return [select id,Config_Data__c from Dynamic_UI_Elements__c where id='a056F00000pAM1R'];
    }

}